stages:
  - install
  - quality

install:
  stage: install
  image: oven/bun:latest
  script:
    - bun install --frozen-lockfile
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

eslint:
  stage: quality
  image: oven/bun:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull
  script:
    - bun run lint

prettier:
  stage: quality
  image: oven/bun:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull
  script:
    - bun run format:check
