services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    environment:
      POSTGRES_URI: postgresql://postgres:postgres@database:5432/postgres
      DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-supersecretrefresh123}
    depends_on:
      - database

  frontend:
    build: ./Frontend
    ports:
      - "4173:4173"

  database:
    image: postgres:16
    container_name: Volly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Backend/src/database/migrations/000_create_users_table.sql:/docker-entrypoint-initdb.d/01_users.sql

volumes:
  pgdata:
