apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-staging
  namespace: doe25-group-15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-staging
  template:
    metadata:
      labels:
        app: backend-staging
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: backend
          image: registry.chas-lab.dev/chas-challenge-2026/grupp-15/zero-bug-heroes/zero-bug-heroes/backend:staging
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres-staging:5432/postgres
            - name: POSTGRES_URI
              value: postgres://postgres:postgres@postgres-staging:5432/postgres
            - name: CORS_ORIGIN
              value: "https://volly-staging.cc.k3s.chas-lab.dev"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_REFRESH_SECRET
            - name: TURN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: TURN_SECRET
            - name: TURN_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: TURN_HOST
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-staging
  namespace: doe25-group-15
spec:
  selector:
    app: backend-staging
  ports:
    - port: 3001
      targetPort: 3001
