apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: staging-ingress
  namespace: doe25-group-15
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`staging-volly.labb.k3s.chas-lab.dev`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: security-headers-staging
        - name: api-rate-limit-staging
      services:
        - name: backend-staging
          port: 3001
    - match: Host(`staging-volly.labb.k3s.chas-lab.dev`)
      kind: Rule
      middlewares:
        - name: security-headers-staging
      services:
        - name: frontend-staging
          port: 3000
  tls: {}
