apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: production-ingress
  namespace: doe25-group-15
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`volly.labb.k3s.chas-lab.dev`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: security-headers-production
        - name: api-rate-limit-production
      services:
        - name: backend-production
          port: 3001
    - match: Host(`volly.labb.k3s.chas-lab.dev`)
      kind: Rule
      middlewares:
        - name: security-headers-production
      services:
        - name: frontend-production
          port: 3000
  tls: {}
