apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers-production
  namespace: doe25-group-15
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    customResponseHeaders:
      X-Robots-Tag: "none"
      Server: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-rate-limit-production
  namespace: doe25-group-15
spec:
  rateLimit:
    average: 100
    burst: 50
