apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-production
  namespace: doe25-group-15
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-production
  namespace: doe25-group-15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-production
  template:
    metadata:
      labels:
        app: postgres-production
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc-production
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-production
  namespace: doe25-group-15
spec:
  selector:
    app: postgres-production
  ports:
    - port: 5432
      targetPort: 5432
