apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-production
  namespace: doe25-group-15
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-production
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
